/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.connectionController;
import model.studentRecord;
import model.studentCourse;
import model.studentSection;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author LordD
 */
public class adminDashboard extends javax.swing.JFrame {
    // TODO :: FIX THE UPDATE TABLE FOR SECTION AND COURSE
    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
        
        // CONNECT TO DATABASE
        connectionController conn = new connectionController();
        conn.DBconnect();
        
        updateTable();
        updateCoursebox();
//        updateSectionbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        recordScrollTable = new javax.swing.JScrollPane();
        recordTable = new javax.swing.JTable();
        DetailPanel = new javax.swing.JPanel();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        sectionCBox = new javax.swing.JComboBox<>();
        idTField = new javax.swing.JTextField();
        firstnameTField = new javax.swing.JTextField();
        courseCBox = new javax.swing.JComboBox<>();
        insertNameLabel = new javax.swing.JLabel();
        insertIdLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        lastnameTField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        studentRecordTitle = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        leftBTN = new javax.swing.JButton();
        rightBTN = new javax.swing.JButton();
        selectionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "STUDENT ID", "FIRSTNAME", "LASTNAME", "SECTION", "COURSE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordTableMouseClicked(evt);
            }
        });
        recordScrollTable.setViewportView(recordTable);

        addBTN.setText("ADD");
        addBTN.setMaximumSize(new java.awt.Dimension(75, 23));
        addBTN.setMinimumSize(new java.awt.Dimension(75, 23));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        updateBTN.setText("UPDATE");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearForm(evt);
            }
        });

        courseCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCBoxActionPerformed(evt);
            }
        });

        insertNameLabel.setText("INSERT NAME");

        insertIdLabel.setText("INSERT ID");

        sectionLabel.setText("SECTION");

        courseLabel.setText("COURSE");

        lastnameLabel.setText("INSERT LASTNAME");

        studentRecordTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentRecordTitle.setText("STUDENT RECORD");

        javax.swing.GroupLayout DetailPanelLayout = new javax.swing.GroupLayout(DetailPanel);
        DetailPanel.setLayout(DetailPanelLayout);
        DetailPanelLayout.setHorizontalGroup(
            DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailPanelLayout.createSequentialGroup()
                        .addComponent(lastnameLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailPanelLayout.createSequentialGroup()
                        .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DetailPanelLayout.createSequentialGroup()
                                .addComponent(sectionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseLabel))
                            .addComponent(lastnameTField)
                            .addComponent(firstnameTField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTField)
                            .addGroup(DetailPanelLayout.createSequentialGroup()
                                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(addBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(studentRecordTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addGroup(DetailPanelLayout.createSequentialGroup()
                                .addComponent(sectionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DetailPanelLayout.createSequentialGroup()
                                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(insertIdLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insertNameLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))))
        );
        DetailPanelLayout.setVerticalGroup(
            DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentRecordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstnameTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLabel)
                    .addComponent(sectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBTN)
                    .addComponent(clearBTN))
                .addGap(34, 34, 34))
        );

        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Search :");

        leftBTN.setText("<");
        leftBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBTNActionPerformed(evt);
            }
        });

        rightBTN.setText(">");
        rightBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBTNActionPerformed(evt);
            }
        });

        selectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectionLabel.setText("STUDENT RECORD");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leftBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(recordScrollTable)))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftBTN)
                            .addComponent(rightBTN)
                            .addComponent(selectionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recordScrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        if(isFormEmpty())
        {
            fillerrorMessage();
            return;
        }
        connectionController CC = new connectionController();
        int selectedRow = recordTable.getSelectedRow();
        if(selectedRow != -1 && 0 == deleteconformation()){
            String studentId = (String) recordTable.getValueAt(selectedRow,1);
            CC.removeFromtable(studentId);
        }
        clearForm();
        updateTable();
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void clearForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearForm
        clearForm();
    }//GEN-LAST:event_clearForm

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        //CHECK IF EMTY
        if(isFormEmpty())
        {
            fillerrorMessage();
            return;
        }
        connectionController CC = new connectionController();
        List<studentRecord> records = CC.fetchrecordtable("T");
        boolean exists = false;

        for (studentRecord record : records) {
            if (record.getSchoolid().equals(idTField.getText())) {
                exists = true;
                break;
            }
        }

        if (exists) {
//            System.out.println("ERROR");
            existerrorMessage();
        } else {
            if(0 == confirmationMessage()){
                CC.insertIntoTable(idTField.getText(), 
                        firstnameTField.getText(), 
                        lastnameTField.getText(),
                        getIndexSection(), 
                        getIndexCourse()
                );
//                System.out.println(idTField.getText()+ " | "+
//                        firstnameTField.getText()+ " | "+
//                        lastnameTField.getText()+ " |Section"+
//                        getIndexSection()+ " |Course" +
//                        getIndexCourse());
            }
            clearForm();
        }
        updateTable();
    }//GEN-LAST:event_addBTNActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        DefaultTableModel dTable = (DefaultTableModel) recordTable.getModel();
        String text = searchBar.getText();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(dTable);
        recordTable.setRowSorter(sorter);
        
        if (text.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_searchBarKeyReleased

    //TABLE CLIKCED
    private void recordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordTableMouseClicked
        int selectedRow = recordTable.getSelectedRow();
        if(selectedRow != -1){
            
            idTField.setText((String) recordTable.getValueAt(selectedRow,1));
            firstnameTField.setText((String) recordTable.getValueAt(selectedRow,2));
            lastnameTField.setText((String) recordTable.getValueAt(selectedRow, 3));
            String selectedSection = (String) recordTable.getValueAt(selectedRow, 4);
            String selectedCourse = (String) recordTable.getValueAt(selectedRow, 5);
            for (int i = 0; i < courseCBox.getItemCount(); i++) {
                if (courseCBox.getItemAt(i).equals(selectedCourse)) {
                    courseCBox.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < sectionCBox.getItemCount(); i++) {
                //                System.out.println(sectionCBox.getItemAt(i) + " | " + selectedSection);
                if (sectionCBox.getItemAt(i).equals(selectedSection)) {
                    sectionCBox.setSelectedIndex(i);
                    break;
                }
            }
        }

    }//GEN-LAST:event_recordTableMouseClicked

    private void rightBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBTNActionPerformed
        sectionDashboard sectiondashboard = new sectionDashboard();
        sectiondashboard.setVisible(true);
        sectiondashboard.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rightBTNActionPerformed

    private void leftBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBTNActionPerformed
        courseDashboard courseDashboard = new courseDashboard();
        courseDashboard.setVisible(true);
        courseDashboard.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_leftBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        connectionController CC = new connectionController();
        int selectedRow = recordTable.getSelectedRow();
        if(selectedRow != -1){
            int id = (int) recordTable.getValueAt(selectedRow,0);
            String schoolid = idTField.getText();
            String firstname = firstnameTField.getText();
            String lastname = lastnameTField.getText();
            CC.updateStudentrecordtable(id,schoolid, firstname , lastname, getIndexSection(), getIndexCourse());
//            System.out.println(id + " | " + schoolid + " | " + firstname + "|" + lastname + "|section:" + getIndexSection() +"|course:"+ getIndexCourse());
        }
        clearForm();
        updateTable();
    }//GEN-LAST:event_updateBTNActionPerformed

    private void courseCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCBoxActionPerformed
        connectionController CC = new connectionController();
        List<studentCourse> courses = CC.fetchstudentcourse();
        String itemCoursebox = courseCBox.getItemAt(courseCBox.getSelectedIndex());
        for(studentCourse course : courses)
        {
//            System.out.println(course.getCourse() + " | " + itemCoursebox);
            if(course.getCourse().equals(itemCoursebox))
            {
                updateSectionbox(course.getId());
            }
        }
    }//GEN-LAST:event_courseCBoxActionPerformed

    // VIEW FUNCTION HERE!
    public void updateTable()
    {
        DefaultTableModel dTable = (DefaultTableModel) recordTable.getModel();
        dTable.setRowCount(0);
        connectionController CC = new connectionController();
        
        List<studentRecord> sRecord = CC.fetchrecordtable("T");
        for(studentRecord record : sRecord)
        {
            int id = record.getId();
            String schoolid = record.getSchoolid();
            String firstname = record.getFirstname();
            String lastname = record.getLastname();
            String section = record.getSection();
            String course = record.getCourse();

            dTable.addRow(new Object[] {id ,schoolid, firstname, lastname, section, course});
        }
    }
    
    public void updateCoursebox()
    {
        connectionController CC = new connectionController();
        List<studentCourse> courses = CC.fetchstudentcourse();
        for(studentCourse course : courses)
        {
            courseCBox.addItem(course.getCourse());
        }
    }
   
    public void updateSectionbox(int courseid)
    {
        sectionCBox.removeAllItems();
        connectionController CC = new connectionController();
        List<studentSection> sections = CC.fetchstudentsection();
        for(studentSection section : sections)
        {
//            System.out.println(courseid);
            if(courseid == section.getSectionnumber())
            {
                sectionCBox.addItem(section.getSectionname());
            }
        }
    }
    
    public int getIndexCourse()
    {
        connectionController CC = new connectionController();
        List<studentCourse> courses = CC.fetchstudentcourse();
        String courseBox = courseCBox.getItemAt(courseCBox.getSelectedIndex());
        System.out.println("get index course: " + courseBox);
        for(studentCourse course: courses)
        {
            if(course.getCourse().equals(courseBox))
            {
                return course.getId();
            }
        }
        return -1;
    }
    public int getIndexSection()
    {
        connectionController CC = new connectionController();
        List<studentSection> sections = CC.fetchstudentsection();
        String sectionBox = sectionCBox.getItemAt(sectionCBox.getSelectedIndex());
        System.out.println("get index section:" + sectionBox);
        for(studentSection section: sections)
        {
            if(section.getSectionname().equals(sectionBox))
            {
                return section.getSectionnumber();
            }
        }
        return -1;
    }
    
    private void clearForm()
    {
        idTField.setText("");
        firstnameTField.setText("");
        lastnameTField.setText("");
        sectionCBox.setSelectedIndex(0); 
        courseCBox.setSelectedIndex(0);
    }
    
    
    
    private boolean isFormEmpty()
    {
        return idTField.getText().equals("") || firstnameTField.getText().equals("") || lastnameTField.getText().equals("");
    }
    // MESSAGES
    private void fillerrorMessage()
    {
        JOptionPane.showMessageDialog(null, "Fill in the blanks", "Error Inserting Data", JOptionPane.OK_OPTION);
    }
    private void existerrorMessage()
    {
        JOptionPane.showMessageDialog(null, "SchoolID AlreadyExist", "Error Inserting Data", JOptionPane.OK_OPTION);
    }
    private int deleteconformation()
    {
        int option = JOptionPane.showConfirmDialog(null,"Delete data?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        return option;
    }
    private int confirmationMessage()
    {
        int option = JOptionPane.showConfirmDialog(null,"Insert data?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        return option;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel DetailPanel;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JComboBox<String> courseCBox;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextField firstnameTField;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel insertIdLabel;
    private javax.swing.JLabel insertNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTField;
    private javax.swing.JButton leftBTN;
    private javax.swing.JScrollPane recordScrollTable;
    private javax.swing.JTable recordTable;
    private javax.swing.JButton rightBTN;
    private javax.swing.JTextField searchBar;
    private javax.swing.JComboBox<String> sectionCBox;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JLabel studentRecordTitle;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
