/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.loginController;
import java.util.List;
import javax.swing.JOptionPane;
import model.adminAccount;
import model.connectionController;
import model.studentAccount;

/**
 *
 * @author LordD
 */
public class loginPage extends javax.swing.JFrame {
    
    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
        connectionController conn = new connectionController();
        // CONNECT TO DATABASE
        conn.DBconnect();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        roleVerify = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        LINE15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(506, 540));
        setPreferredSize(new java.awt.Dimension(506, 540));
        setSize(new java.awt.Dimension(0, 0));

        kGradientPanel1.setkEndColor(new java.awt.Color(73, 196, 239));
        kGradientPanel1.setkStartColor(new java.awt.Color(49, 79, 186));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(514, 542));

        roleVerify.setBackground(new java.awt.Color(242, 242, 242));
        roleVerify.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        roleVerify.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Admin" }));
        roleVerify.setAlignmentX(jLabel1.getAlignmentX());
        roleVerify.setAlignmentY(jLabel1.getAlignmentY());
        roleVerify.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        roleVerify.setMaximumSize(new java.awt.Dimension(93, 32767));
        roleVerify.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                roleVerifyComponentResized(evt);
            }
        });
        roleVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleVerifyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Username");

        LINE15.setAlignmentX(jLabel1.getAlignmentX());
        LINE15.setAlignmentY(jLabel1.getAlignmentY());
        LINE15.setMaximumSize(new java.awt.Dimension(32767, 3));
        LINE15.setMinimumSize(new java.awt.Dimension(100, 3));
        LINE15.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout LINE15Layout = new javax.swing.GroupLayout(LINE15);
        LINE15.setLayout(LINE15Layout);
        LINE15Layout.setHorizontalGroup(
            LINE15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        LINE15Layout.setVerticalGroup(
            LINE15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please enter login details below.");
        jLabel5.setAlignmentX(jLabel1.getAlignmentX());
        jLabel5.setAlignmentY(jLabel1.getAlignmentY());
        jLabel5.setFocusTraversalPolicyProvider(true);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnLogin.setText("SUBMIT");
        btnLogin.setAlignmentX(jLabel1.getAlignmentX());
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Password");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Continue as");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentX(jLabel1.getAlignmentX());
        jLabel2.setAlignmentY(jLabel1.getAlignmentY());
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(LINE15, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addGap(66, 66, 66))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roleVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addComponent(txtPassword)
                            .addComponent(txtUsername)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LINE15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(roleVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        roleVerify.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleVerifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleVerifyActionPerformed

    private void roleVerifyComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_roleVerifyComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_roleVerifyComponentResized

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String role = (String) roleVerify.getSelectedItem();
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        loginController control = new loginController();
        control.handleLogin(role, username, password, this);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed
  
  private void studentLogin(String username, String password) {
         
        connectionController CC = new connectionController();
        List<studentAccount> accounts = CC.fetchstudentaccount(); 
        boolean isVerified = false;
        
        
        for (studentAccount account : accounts) {
            System.out.println(account.getSchoolid() + " : " + username +account.getSchoolid().equals(username)+"|"+account.getLastname() +" : " +password +account.getLastname().equals(password));
            if (account.getSchoolid().equals(username) && account.getLastname().equals(password)) {
                isVerified = true;
                break;
            }
        }
        if (isVerified) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
//            recordDashboard adminDashboard = new recordDashboard();
//            adminDashboard.setLocationRelativeTo(null);
//            adminDashboard.setVisible(true);
            studentDashboard studentdashboard = new studentDashboard();
            studentdashboard.setLocationRelativeTo(null);
            studentdashboard.setVisible(true);
            this.dispose();
        } else{
            JOptionPane.showMessageDialog(this, "Invalid Usernamme or Password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     
    private void adminLogin(String username, String password) {
    
        connectionController CC = new connectionController();
        List<adminAccount> admins = CC.fetchadminaccount(); 
        boolean isVerified = false;

        for (adminAccount admin : admins) {
            System.out.println(admin.getFirstname() + " : " + username + admin.getLastname().equals(username) + "|" +admin.getLastname() + " : " + password + admin.getLastname().equals(password));
            if (admin.getFirstname().equals(username) && admin.getLastname().equals(password)) {
            isVerified = true;
            break;
            }
        }

        if (isVerified) {
            JOptionPane.showMessageDialog(this, "Admin Login Successful!");
            adminHomeDashboard adminhomedashboard = new adminHomeDashboard();
            adminhomedashboard.setLocationRelativeTo(null);
            adminhomedashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LINE;
    private javax.swing.JPanel LINE1;
    private javax.swing.JPanel LINE10;
    private javax.swing.JPanel LINE11;
    private javax.swing.JPanel LINE12;
    private javax.swing.JPanel LINE13;
    private javax.swing.JPanel LINE14;
    private javax.swing.JPanel LINE15;
    private javax.swing.JPanel LINE2;
    private javax.swing.JPanel LINE3;
    private javax.swing.JPanel LINE4;
    private javax.swing.JPanel LINE5;
    private javax.swing.JPanel LINE6;
    private javax.swing.JPanel LINE7;
    private javax.swing.JPanel LINE8;
    private javax.swing.JPanel LINE9;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JComboBox<String> roleVerify;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
